### ISSUE TITLE
Interactive graph inherits color of `revealjs` theme (not desired)

### ISSUE THREAD

**Issue by rleyvasal** [rstudio/revealjs#104]
# Issue
Interactive plots inherit the colors of `revealjs` theme. 
Note:  When the plot is wrapped in a `widgetframe` the colors are not inherited. 

# Expected
Interactive graphs should not be affected by theming of `revealjs` 

````markdown
---
title: "Untitled"
date: ""
author: ""
output: 
  revealjs::revealjs_presentation:
    incremental: true
    highlight: pygments
    self_contained: false
    theme: black
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Interactive plot without `widgetframe`

```{r}
library(pacman)
p_load(tidyverse, echarts4r, widgetframe)
```
  
```{r echo=FALSE}
mtcars|>
  e_charts()|>
  e_boxplot(mpg)|> 
  e_boxplot(disp) |>
  e_boxplot(hp) |>
  e_title("boxplots") |> e_tooltip(trigger = "axis") 
```

# Interactive plot with `widgetframe`

```{r}
plot_1 <- mtcars|>
  e_charts()|>
  e_boxplot(mpg)|> 
  e_boxplot(disp) |>
  e_boxplot(hp) |>
  e_title("boxplots") |> e_tooltip(trigger = "axis") 
frameWidget(plot_1)
```
````

![interactive_graph_inherits](https://user-images.githubusercontent.com/61335136/130534731-200c3c70-6126-4b08-adf4-92293ce5bccb.gif)

**Comment by cderv** [comment]
This is not something related to revealjs only. See this example using `html_document()`
````markdown
---
title: "echarts4r background"
output: html_document
---

```{r}
library(echarts4r)
```

```{css, echo = FALSE}
body {
  background-color: lightgrey;
}
```


```{r echo=FALSE}
mtcars|>
  e_charts()|>
  e_boxplot(mpg)|> 
  e_boxplot(disp) |>
  e_boxplot(hp) |>
  e_title("boxplots") |> 
  e_tooltip(trigger = "axis") 
```

````

I think this is expected for echarts plots. 
The documentation says, they have no background: https://echarts.apache.org/en/option.html#backgroundColor
This means they will inherit the one from the document they are included into I believe. 
Background color can be set using `e_color()` it seems , and in that case it will be fixed. 

````diff
mtcars|>
  e_charts()|>
  e_boxplot(mpg)|> 
  e_boxplot(disp) |>
  e_boxplot(hp) |>
  e_title("boxplots") |> 
-  e_tooltip(trigger = "axis")
+  e_tooltip(trigger = "axis") |>
+  e_color(background = "white")
````

So I don't think this is anything specific to revealjs but it is related to this specific widget. The use of widgetframe will isolate the widget and that is why you get the expected result and it will not inherit value from the document. 

Hope it helps understand. Does it make sense ?

**Comment by rleyvasal** [comment]
Thanks @cderv, I was not aware there was no background on `echarts` plots.  I get the expected result when I set the background color on my plot.
