### ISSUE TITLE
No slide breaks in RStudio 0.99.467

### ISSUE THREAD

**Issue by kylelundstedt** [rstudio/revealjs#12]
I'm using 0.99.441 on my Retina iMac, and 0.99.467 on my Retina MacBook. I've run the same RevealJS RMarkdown code (I've used the unchanged RevealJS presentation template selected in RStudio) on both systems.

On 0.99.41, the RevealJS presentation processes normally, and my HTML slides look perfect. Running the exact same code on 0.99.467 generates no errors; however, a standard HTML page is generated, where there are no slide breaks based on each section header.

You can duplicate my YAML header exactly by creating a new RMarkdown document from RStudio (File -> New File -> RMarkdown) and choosing "Reveal.js Presentation" from the "From Template" tab in the dialog box.

I've confirmed that the rmarkdown package on both systems is version 0.7 (and the revealjs package is 0.5), so I don't think that's the issue. Moreover, since "Reveal.js Presentation" now appears on the "From Template" menu, shouldn't it work regardless?

The RMarkdown console in both 0.99.41 and 0.99.467 appears exactly the same. So, I'm baffled about why the exact same RMarkdown file produces different output. Any ideas?

**Comment by znmeb** [comment]
@kylelundstedt  Are you seeing any error messages? I just tried to reproduce this on Fedora Linux (rstudio 0.99.467) and got an error from the 'Knit' button:

```
output file: revealjs.knit.md

Fetching https://fonts.googleapis.com/css?family=News+Cycle:400,700...
pandoc: Could not fetch https://fonts.googleapis.com/css?family=News+Cycle:400,700
user error (https not supported)
Error: pandoc document conversion failed with error 67
Execution halted
```

**Comment by kylelundstedt** [comment]
@znmeb I'm not seeing any errors at all.
