### ISSUE TITLE
Add html plot to slide in `rmarkdown`

### ISSUE THREAD

**Issue by rleyvasal** [rstudio/revealjs#153]
I want to insert plot.html (created in python Plotly) into my slides, but there is no option to do it in `rmarkdown` 

Inserting the plot works into slides with the following code:

```html
<style>
.p_iframe iframe {
    width:90%;
    height:576px;
}

</style>

<div class="p_iframe">
<iframe frameborder="0" seamless='seamless' scrolling=no src="plot.html"></iframe>
</div>
```

Is there an easier way to do the above in `rmarkdown` ?

the following does not work well(plot squeezed):

```rmarkdown

# iframe not working to insert html

<iframe src=""plot.html"> </iframe>

```

**Comment by cderv** [comment]
You should be able to use HTML code inside your Markdown document. Can you share `plot.html` so that I can try ? 
What is not working exactly ? Can you share a screenshot of the slide ?

**Comment by rleyvasal** [comment]
using `iframe`  plot does not show

![iframe](https://user-images.githubusercontent.com/61335136/166956536-52605d2b-e073-4586-abf0-924fcdcb0cb3.PNG)


using `HTML` the plot shows

![html_slide](https://user-images.githubusercontent.com/61335136/166956568-5eb9a30f-37dd-49ef-a62d-a7471cbfac51.PNG)


**Code to replicate**
```rmarkdown
# HTML plot iframe not working to insert html

<iframe src="plot.html"> </iframe>


# HTML Plot {data-transition="zoom"}


<style>
.p_iframe iframe {
    width:90%;
    height:576px;
}

</style>


<div class="p_iframe">
<iframe frameborder="0" seamless='seamless' scrolling=no src="plot.html"></iframe>
</div>
```

**Comment by cderv** [comment]
I don't have `plot.html` to replicate.

**Comment by rleyvasal** [comment]
[plot.zip](https://github.com/rstudio/revealjs/files/8632824/plot.zip)

**Comment by rleyvasal** [comment]
Problem solved: just had to add class="stretch" as shown in code below. Feel free to close this issue

```html
<iframe class="stretch" src="plot.html"> </iframe>
```

**Comment by cderv** [comment]
Oh ok. so that is a matter of CSS for you inserted iframe. stretch class will trigger a feature in reveal to compute width to fit the available space. 

Glad it works for this !

**Comment by rleyvasal** [comment]
Adding a pause `. . .` before iframe plot causes the same issue - html image squeezed and cannot be seen. 

```rmarkdown

. . .

<iframe class="stretch" src="plot.html"> </iframe>
````
