### ISSUE TITLE
Vertical slides separator?

### ISSUE THREAD

**Issue by julou** [rstudio/revealjs#16]
Hello, 

The readme states that "You can create a slide show broken up into sections by using the # and ## heading tags". This works for me as long as the upper level slide has only a title (i.e. no content).

Is there a way to specify vertical slides more explicitely? as eg in reveal.js external markdown (data-separator="^\n\n\n", data-separator-vertical="^\n\n")

Thanks for your help,
Thomas

**Comment by julou** [comment]
Here is a minimal example.
The following produces "vertical" slides:

```
# In the morning

## Getting up

- Turn off alarm
- Get out of bed

## Breakfast

- Eat eggs
- Drink coffee

# In the evening

## Dinner

- Eat spaghetti
- Drink wine
```

The following produces slides with 2 levels of title:
```
# In the morning

- because it's early

## Getting up

- Turn off alarm
- Get out of bed

## Breakfast

- Eat eggs
- Drink coffee

# In the evening

## Dinner

- Eat spaghetti
- Drink wine
```

**Comment by junkka** [comment]
The vertical slides can be controlled through the <section> </section> tags.

    # 
    <section>
    <h2>Title of first vertical slide</h2>
     The body of the first slide
    </section>
    <section>
    <h2>Title of second vertical slide</h2>
     The body of the second vertical slide
    </section>

    # A new horizontal slide

    The body of the second horizontal slide

**Comment by julou** [comment]
It kind of works… tanks!

What if I want to have vertical slides with h1 level title only (as e.g. in the [reveal.js demo](http://lab.hakim.se/reveal-js/#/2/1))?

**Comment by julou** [comment]
After looking in more details, I realised that the pandoc>html conversion is totally in the hands of pandoc (the rules to create a new slide are nicely explained in the [documentation](http://pandoc.org/demo/example9/producing-slide-shows-with-pandoc.html)). What would really increase the flexibility would be to allow the user to set its own slide_level argument to pandoc.

Would you consider parsing this from the yaml header?  (as e.g. [beamer_presentation does](http://rmarkdown.rstudio.com/beamer_presentation_format.html#table-of-contents-and-slide-level)…)

**Comment by julou** [comment]
My apologies: it totally works!

NB to other readers: use h1 if you want the same title level as in other slides…

**Comment by whizzalan** [comment]
Is there some way that render slides with first header not only title?

```
# In the morning

- because it's early
- there is no content....

## Getting up

- Turn off alarm
- Get out of bed

## Breakfast

- Eat eggs
- Drink coffee

# In the evening

## Dinner

- Eat spaghetti
- Drink wine
```

**Comment by whizzalan** [comment]
like this 
<img width="1062" alt="screen shot 2017-06-27 at 11 42 54 am" src="https://user-images.githubusercontent.com/5684420/27570057-c520b232-5b2d-11e7-96b5-a536ebd45c34.png">

**Comment by qcha0s** [comment]
You can use a fragment for heading 2's -> 

`## In the morning {.fragment}`

It doesn't work with heading 1's however. 

you can also use `>- ` for your bullet points to make them fragments

**Comment by katossky** [comment]
I indeed appreciate the ability to control slide jumps as I please on Hackmd (https://hackmd.io/c/tutorials/%2Fs%2Fhow-to-create-slide-deck).

`----` for a new series of slides
`---` for a new vertical slide in a given series

I also feel like one should be able to add content on the same slide as a level-1 title.
Could this be controlled by an option in YAML front-matter? Like `auto-slide-jumps: false`?

As I far I understand from the `reveal.js` documentation (https://github.com/hakimel/reveal.js#markdown), the default is `\n\n\n` for horizontal / section jumps and `\n\n` for vertical jumps.

> Note the separator arguments which determine how slides are delimited in the external file: the `data-separator` attribute defines a regular expression for horizontal slides (defaults to `^\r?\n---\r?\n$`, a newline-bounded horizontal rule) and `data-separator-vertical` defines vertical slides (disabled by default). The `data-separator-notes` attribute is a regular expression for specifying the beginning of the current slide's speaker notes (defaults to `notes?:`, so it will match both "note:" and "notes:").

**Comment by joymon** [comment]
I tried -- as mentioned in the below link and it created vertical slides.
[http://vishalgupta.me/md-slides/](http://vishalgupta.me/md-slides/)

**Comment by cderv** [comment]
For this kind of feature we rely on pandoc support to structure the slide show
* https://pandoc.org/MANUAL.html#structuring-the-slide-show
* https://pandoc.org/MANUAL.html#option--slide-level

With `revealjs::reveal_presentation()`, the default is currently `slide_level = 2`, which will allow to create new horizontal slides with h1 `#` and new vertical slides with h2 `##`. 

With last Pandoc version (2.14.2), `slide_level = 0` is now allowed, and will allow to separate slides using `---`. However, I don't think there is a way to create vertical slides in this case. 

For better support of reveal.js capabilities, I believe this should be done into pandoc directly. 

Currently, this works to create 2D slides, each ## will create vertical slides with h2 and will be nested under the first slide with h1

````markdown
---
title: "Test"
output: revealjs::revealjs_presentation
---

# In the morning

- because it's early
- there is no content....

## Getting up

- Turn off alarm
- Get out of bed

## Breakfast

- Eat eggs
- Drink coffee

# In the evening

## Dinner

- Eat spaghetti
- Drink wine
````
