### ISSUE TITLE
upgrade to reveal 3.0

### ISSUE THREAD

**Issue by timelyportfolio** [rstudio/revealjs#2]
What do you think about upgrading the reveal.js to [3.0](https://github.com/hakimel/reveal.js/releases/tag/3.0.0)?  I have tried locally and seems like dropping in new js/css works without breaking anything.  Here is the guide to [migration](https://github.com/hakimel/reveal.js/wiki/Migrating-to-reveal.js-3.0.0) which is really only necessary if you want your presentation to look "old"/"original".

**Comment by jjallaire** [comment]
I don't have time to do this but I'd most certainly entertain a PR to!

**Comment by timelyportfolio** [comment]
Ok, I made this forked [branch](https://github.com/timelyportfolio/revealjs/tree/reveal3.0.0).  It seems to work on the one presentation I have and the skeleton in the package and the Readme.md examples.  I unfortunately could not easily find more to test.  Do you know of any others I can use to test?

Release notes for reveal 3.0.0 contain a helpful [migration guide](https://github.com/hakimel/reveal.js/wiki/Migrating-to-reveal.js-3.0.0).  Nothing really breaks.  Guide just shows how you can get back to the old look/feel if for some strange reason you want that.

**Comment by timelyportfolio** [comment]
@cainesap I noticed you did a demo in October.  Your demo works fine with this change.  Do you have other revealjs presentations that could help us test?  Thanks.

**Comment by jjallaire** [comment]
@cboettig  I seem to recall that you might be using reveal.js for R Markdown presentations. How does the new version work with your stuff?

**Comment by cainesap** [comment]
@timelyportfolio hi, sorry, no others atm, but the demo tried to cover many features, so that's good news if it works ok in 3.0

**Comment by ramnathv** [comment]
Why not leave both in? That is what I did with `slidify`. Setting `framework: revealjs3` would switch to using the new framework. Over time, one can deprecate the older version as people switch to the new one.

**Comment by jjallaire** [comment]
My guess is that there aren't a ton of users of the revealjs package (since
it's only on GitHub and not promoted anywhere) so it might be better to
just move on and not sweat supporting the old version.

**Comment by cboettig** [comment]
Yup, :+1: to just moving on with 3.0

**Comment by znmeb** [comment]
Yep - I'm using the Reveal package from GitHub and am fine with the upgrade. I'll test it when it goes live.

**Comment by jjallaire** [comment]
@timelyportfolio Can you send a PR for the upgrade?

**Comment by znmeb** [comment]
Testing it now - the theme names have changed and I'm still checking on whether they all work for my use case but it does seem to function.
