### ISSUE TITLE
theme: beige is missing resources

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/revealjs#23]
pandoc: Could not fetch /usr/local/lib/R/site-library/revealjs/reveal.js-3.2.0/css/theme/../../lib/font/league_gothic-webfont.eot
    /usr/local/lib/R/site-library/revealjs/reveal.js-3.2.0/css/theme/../../lib/font/league_gothic-webfont.eot: openBinaryFile: does not exist (No such file or directory)

Looks like it's a font name issue `league_gothic-webfont.eot` vs `league_gothic.eot`

**Comment by jjallaire** [comment]
fixed via https://github.com/rstudio/revealjs/commit/091cb1247867f9f426748686d858a34f183b5d89

**Comment by giorjet** [comment]
Hi, I have the same problem of @hrbrmstr and I don't understand the solution of @jjallaire. I tried to reinstall rstudio, reveal and also to put the font league_gothic-webfont.eot in the font folder but nothing: beige, solarized and legue don't work. could someone help?

**Comment by jjallaire** [comment]
You may need to reinstall from GitHub (the development version) as the fix
isn't on CRAN yet:

devtools::install_github("rstudio/revealjs")

**Comment by giorjet** [comment]
Super! thank so much
