### ISSUE TITLE
Allow multi-column output

### ISSUE THREAD

**Issue by FvD** [rstudio/revealjs#24]
Is there any way to request multi-column output? Based on the revealjs examples from [Zev Ross](http://zevross.com/blog/2014/11/19/creating-elegant-html-presentations-that-feature-r-code/) and [Ramnath Vaidyanathan](http://bl.ocks.org/ramnathv/8421232) I expected the following syntax to work:

```
--- &twocol

## Two Column Slide

*** =left
Left Column

*** =right
Right Column

*** =fullwidth
Back to one column
```
But it does not. The rmarkdown way to put a horizontal rule (`***`) between the column content does not work either.

**Comment by jjallaire** [comment]
Yeah, those are slidify features but aren't implemented in the pandoc
reveal.js format.

**Comment by FvD** [comment]
Thanks, I see it now in [pandoc issue 1710](https://github.com/jgm/pandoc/issues/1710).
