### ISSUE TITLE
Borders Graphics Output R - css customization

### ISSUE THREAD

**Issue by mh74** [rstudio/revealjs#25]
Great Framework to have with(in) R/RStudio, Any hint as to how I can change the border color of the graphics output. The color changes according to the theme and seems to be the same color as the standard text. Example: When a ggplot graphic is rendered and put into the presentation, there is a css border in the slides around the plot

**Comment by jjallaire** [comment]
Here are the docs on adding custom CSS:
http://rmarkdown.rstudio.com/revealjs_presentation_format.html#custom_css

So you'll probably need CSS something like this to modify how images are
displayed:

.reveal section img {

}

I haven't done this myself so some experimentation may be required!

**Comment by mh74** [comment]
Thanks for your suggestion JJAllaire, it worked. This is what I used:

.reveal section img{
    border-color:#000;
  }

**Comment by jjallaire** [comment]
Great, glad it worked!

**Comment by jdstorey** [comment]
On a related note, if you want to remove all borders you can do:

```
.reveal section img { 
  background:none; 
  border:none; 
  box-shadow:none; 
  }
```
