### ISSUE TITLE
Rendering presentation from console/command-line

### ISSUE THREAD

**Issue by chendaniely** [rstudio/revealjs#27]
Not sure if it would be helpful in the documentation to mention rendering presentations from the console:

```r
rmarkdown::render('my_reveal_presetntaion.Rmd')
```

and command line:

```bash
Rscript -e "rmarkdown::render('my_reveal_presetntaion.Rmd')"
```

It took me a while to realize what that magical `knit` button did in rstudio.

I can submit a PR if it is found to be useful.

**Comment by jjallaire** [comment]
Yes, a PR for that would be great!
