### ISSUE TITLE
Custom CSS not working

### ISSUE THREAD

**Issue by DataWookie** [rstudio/revealjs#29]
Hi,

Great to be able to generate Reveal.js presentations from within RStudio! Thank you.

According to [this](http://rmarkdown.rstudio.com/revealjs_presentation_format.html#custom_css) we should be able to include custom CSS using something like the following in the YAML header:

```
---
output:
  revealjs::revealjs_presentation:
    css: styles.css
---
```

I've tried this and it's completely ignored. I note that there is no mention of this facility on the project's GitHub page. Has this feature not been implemented?

Best regards,
Andrew.

**Comment by jjallaire** [comment]
You have to do some special qualification of your CSS classes to get this to work. Docs are here: 

http://rmarkdown.rstudio.com/revealjs_presentation_format.html#custom_css

Let me know if this works the way you expect it to.

**Comment by DataWookie** [comment]
Hi,

Thanks for getting back to me so promptly. Yes, I am using the correct CSS syntax (currently I am getting around this issue by including extra HTML into the header with <style></style> tags. But this is not ideal and I would prefer to include a CSS file, which is a more direct solution.

The problem is that the CSS is not actually getting included in the HTML file being produced by knitr.

Thanks,
Andrew.

**Comment by jjallaire** [comment]
You might not be running the most up to date version of the package, in
this simple repro the CSS is indeed included and applied:

https://gist.github.com/jjallaire/41847fb1340f0d6d2f74

**Comment by DataWookie** [comment]
Quite so. I installed directly from GutHub and this issue was resolved. Thank you.

**Comment by gdrolet** [comment]
Kind of related: everything revealjs-related I put in the YAML is not honored. I need to put all revealjs options the call `rmarkdown::render() ` for them to be considered. I just installed revealjs from github (`install_github("rstudio/revealjs"`). 

Anything I'm doing wrong?
