### ISSUE TITLE
Template html from Pandoc?

### ISSUE THREAD

**Issue by cfriedrichh** [rstudio/revealjs#31]
Please consider changing the current template to the template from pandoc which includes dependencies and thereby allows for the speaker notes mode.

https://github.com/jgm/pandoc-templates/blob/feffd7c64abab863abd3f6458d1c445d6bfe7fc4/default.revealjs

**Comment by cderv** [comment]
Speaker notes were added in 82a8deeec03225ec4aeef73060d582bf0c101309
