### ISSUE TITLE
How to invoke speaker view?

### ISSUE THREAD

**Issue by thercast** [rstudio/revealjs#33]
I'm planning a presentation for next month and `revealjs` looks like an excellent framework to try.  I was browsing the [official demo](http://lab.hakim.se/reveal-js/#/) and saw that you can invoke a [speaker view](http://lab.hakim.se/reveal-js/#/19) by pressing `s` to launch the view with speaker notes.  I tried invoking the speaker view using the template that's launched when creating a new revealjs presentation, but hitting the `s` key did nothing.  Is there an option I can specificy to enable use of this feature.  FWIW the official demo also lets me zoom in by holding `alt` and clicking, but that did not work in this case either.

**Comment by jjallaire** [comment]
Speaker view unfortunately doesn't work with our reveal.js implementation
because it requires adding a plugin (which we can't do right now).

**Comment by BruceZhaoR** [comment]
@thercast 
Here is a reproducible solution:
```yaml
output:
  revealjs::revealjs_presentation:
    center: true
    self_contained: false
    lib_dir: libs
    includes:
      after_body: plugins.html
```
The `plugins.html`:
```html
<script>
 Reveal.initialize({
	// Optional reveal.js plugins
	dependencies: [
		{ src: 'libs/reveal.js-3.2.0/plugin/zoom-js/zoom.js', async: true },
		{ src: 'libs/reveal.js-3.2.0/plugin/markdown/marked.js', async: true },
		{ src: 'libs/reveal.js-3.2.0/plugin/notes/notes.js', async: true }
	]
});
</script>
```
The `test.rmd`:
```rmd
    ## Test slide 1

    ```{r}
    head(cars)
    ```
    <aside class="notes">
    Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
    </aside>

    ## Test slide 2

    > "Good luck, my friend!"
```
**After kniting, press `S` key  to try it out, and the try press `alt` + click on any element to zoom in on it.**

**Comment by jjallaire** [comment]
I just added formal support for the "notes", "search", and "zoom" plugins here: https://github.com/rstudio/revealjs/commit/82a8deeec03225ec4aeef73060d582bf0c101309

Docs are here: https://github.com/rstudio/revealjs#reveal-plugins

I did this via whitelisting because some of the plugins ("math", "highlight", and "markdown") actually conflict with built-in features of the format. If there are other plugins which you think make sense to include please feel free to submit a PR.

**Comment by thercast** [comment]
Thank you @jjallaire!  I just tried the new version with my presentation and the plugins work perfectly.  So far these three plugins are all I need but as I use this more in the future I'll make a PR for any new ones that should be added.

**Comment by cryoguy** [comment]
I can not seem to get the speaker notes to work.  It will hide, but nothing happened when pressing "s" key.  Any thoughts or help?

---
title: "Habits"
output:
  revealjs::revealjs_presentation:
  self_contained: false
  reveal_plugins: ["notes", "search"]
---
  
  
# In the morning
  
## Getting up
  
- Turn off alarm
- Get out of bed

<aside class="notes">
        Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
</aside>

**Comment by jjallaire** [comment]
You might have a problem with the indentation of your YAML, try:

```yaml
---
title: "Untitled"
output: 
  revealjs::revealjs_presentation:
    self_contained: false
    reveal_plugins: ["search", "zoom", "notes"]
---
```

Also be sure you've installed the latest version from GitHub master.

**Comment by cryoguy** [comment]
Thanks, @jjallaire 
That was the problem.
