### ISSUE TITLE
surround strings in slideNumber (reveal_options) with '

### ISSUE THREAD

**Issue by rnuske** [rstudio/revealjs#38]
revealjs supports different styles of slide numbers. To switch slide numbers on/off and to choose a different slide number style via the same option, slideNumber can contain either a [boolean or a string](https://github.com/hakimel/reveal.js#slide-number).

The translation of the slideNumber from the YAML header in the rmarkdown-file to the Reveal.initialize({})-Block in the HTML-file never surrounds its content with ' ' .  Thus, only true/false is understood by rveal.js. 

At the moment the YAML-header reveal_options-line `slideNumber: true` becomes in the HTML-file:
```
Reveal.initialize({
  // Display the page number of the current slide
  slideNumber: true
});
```

This is great but `slideNumber: 'c/t' ` should become `slideNumber: 'c/t'` and not `slideNumber: c/t`

It would be great if during the translation of slideNumber from YAML to Reveal.initialize `'` could be added automagically to everything not `true` or `false`.

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/revealjs/commit/a075efe27bb5cfe11ab3ddefb7a01aa8ccbaff4f

**Comment by rnuske** [comment]
wow, impressed by your speed. 
Thanks a lot!
