### ISSUE TITLE
Dygraphs not rendering in revealjs presentation

### ISSUE THREAD

**Issue by hherrada** [rstudio/revealjs#41]
Any idea why?

Example:

`---`
`author:`
`date:`
`output:` revealjs::revealjs_presentation
`---`

`# Dygraph Test`

````{r test}`

`library(dygraphs)`
`library(xts)`

`dygraph(xts(rnorm(10),order.by=as.Date(1:10)))`

**Comment by jjallaire** [comment]
You have no `title` field, you are using an `#` rather than a `##` to delimit your slide, and you haven't set `echo=FALSE` in your chunk options.

**Comment by hherrada** [comment]
I'm confused then. Doing `##` instead of `#` is the only thing I changed to make the widget appear on the slide. Great. However [these ](http://rmarkdown.rstudio.com/revealjs_presentation_format.html)guidelines suggestedthe use of `#` to render the widget on a first level slide AND the used of `##` to render the widget on a second level slide. The following code renders the chart in the second level only. Is it possible to render the widget under `#` as well?

Thank you!

`---`
`output: revealjs::revealjs_presentation`
`---`

`# Dygraph Level 1`

````{r one}`
`library(dygraphs)`
`dygraph(ldeaths)`

`## Dygraph Level 2`

````{r two}`
`dygraph(ldeaths)`

**Comment by mwillumz** [comment]
No content on level one slides (just headers) is an incredibly frustrating limitation of pandoc if I remember correctly.  

I'd love to do the same thing fwiw.
