### ISSUE TITLE
chalkboard plugin

### ISSUE THREAD

**Issue by ekstroem** [rstudio/revealjs#42]
Hi,

I'd like to add the [chalkboard](https://github.com/rajgoel/reveal.js-plugins/tree/master/chalkboard) plugin to my reveal presentations. From what I can gather there are certain situations where the "standard" `reveal.js` plugins might not play nicely with the revealjs package. 

My questions are: 
1. Has anyone looked at this already?
2. If not: if there anything I should be aware of if I try to add the plugin to the package?

If I succeed I'll make sure to make a PR.

**Comment by jjallaire** [comment]
Implemented here: https://github.com/rstudio/revealjs/commit/375805c0b9c5a0c1941a76d1cd684810dd92c330

Docs here: https://github.com/rstudio/revealjs#reveal-plugins

**Comment by ekstroem** [comment]
Whoa. That was fast (and thank you!)

**Comment by ekstroem** [comment]
Just in case someone else tries to run this by adding the plugin to an *existing* `Rmd` file: Make sure to remove the `libs` directory to ensure that the directory is recreated and the new plugins are copied to the directory. At least I had to (and it took me a little while to figure out why it wasn't working).

**Comment by Emaasit** [comment]
@ekstroem Thanks for this catch!!!!!!. I was struggling for almost 15 mins wondering why the chalkboard icon was not appearing. Then I saw your comment here. It worked.

@jjallaire Could you maybe include a note about this in the documentation?
