### ISSUE TITLE
Absolute path to local revealjs file "html5shiv.js" contained in generated HTML file despite "self_contained: true"

### ISSUE THREAD

**Issue by aryoda** [rstudio/revealjs#43]
In issue #8 the **printing slides is broken without the proper path to the revealjs pdf.css and print.css** was fixed in June 2017.

Later the **dynamic inclusion of pdf css for self_contianed (#8)** was fixed in Version: 0.8.9000 for the same issue (Jan 2017).

If I now create a new Rmd file in RStudio 0.99.902 using the package `revealjs` with the fixed version 0.8.9000

```
---
title: "Untitled"
author: "Author"
date: "January 8, 2017"
output:
        revealjs::revealjs_presentation:
        self_contained: true
---

Hello world!
```

the generated HTML file contains an absolute path to a local revealjs file:

```
<!--[if lt IE 9]>
<script src="/home/<user name>/R/x86_64-pc-linux-gnu-library/3.3/revealjs/reveal.js-3.3.0/lib/js/html5shiv.js"></script>
<![endif]-->
```
This is not only a (really small) security issue for slides published in the internet but will also not work if you open the slide HTML file on a different computer than the one where you created the slides.

Is there a way of getting rid of this absolute file reference in case of output option `self_contained: true`?

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/revealjs/commit/f93c95fb48edaa03dc49b145be038b7c126ad2c6

**Comment by aryoda** [comment]
THX!

**I can confirm that the issue is fixed.**

I have tested ist by installing the fixed dev version using

`devtools::install_github("revealjs", "rstudio")`

and generated my slides HTML file again with `self_contained: true` (as well as `self_contained: false).

I can no longer find any reference to my home folder via an absolute path.
