### ISSUE TITLE
Note Separator not triggering

### ISSUE THREAD

**Issue by spm1001** [rstudio/revealjs#45]
Inserting notes using `<aside class="notes">This is a speaker note</aside>`
works fine, but I can't seem to make it work using the note separator `Note:`

Tested using:
```
---
output:
  revealjs::revealjs_presentation:
    self_contained: false
    reveal_plugins: ["notes"]
---

## Title
Here is some content...

Note:
This will only display in the notes window.
```
Expected the 'This will only display' to be hidden, but it was included in the slide. 
```
---
output:
  revealjs::revealjs_presentation:
    self_contained: false
    reveal_plugins: ["notes"]
---
## Title
Here is some content...

<aside class="notes">
This will only display in the notes window.
</aside>
```
Works as expected. Both work fine in vanilla reveal.js. 

I'd love to be able to do this in the RMarkdown flavour as it makes the text more readable.

**Comment by jjallaire** [comment]
Didn't realize that reveal had that functionality! 

We'd probably need to have either pandoc's reveal.js binding support this or add a post-processing step to look for `Note:` and convert it to an aside. Won't have time to do this in the near future but we'd certainly entertain a pull request!

**Comment by katossky** [comment]
Reveal.js [says](https://github.com/hakimel/reveal.js#speaker-notes) that:

> If you're using the external Markdown plugin, you can add notes with the help of a special delimiter:
> 
>     <section data-markdown="example.md" data-separator="^\n\n\n" data-separator-vertical="^\n\n" data-separator-notes="^Note:"></section>
>     
>     # Title
>     ## Sub-title
>     
>     Here is some content...
>     
>     Note:
>     This will only display in the notes window.

But I am not sure where it could be inserted.

**Comment by katossky** [comment]
I tried with [Pandoc's specifications](http://pandoc.org/MANUAL.html#speaker-notes) and it doesn't work either.

> ```
> ::: notes
> 
> This is my note.
> 
> - It can contain Markdown
> - like this list
> 
> :::
> ```

**Comment by cderv** [comment]
I think Speaker notes are now working using the fenced div syntax as documented here: 
https://pandoc.org/MANUAL.html#speaker-notes
This produces a document with speaker notes using current version of **revealjs**

````markdown
---
title: "Test"
output: 
  revealjs::revealjs_presentation:
    self_contained: false
    reveal_plugins: notes
    keep_md: true
---

# Main header

::: notes
Main header notes
:::

## Subheader 1

::: notes
Subheader 1 notes
:::

## Subheader 2

::: notes
Subheader  notes
:::
````

I believe this is a good and easy way to write speaker notes and I don't think there is benefits to use the other syntax
````
## Title
Here is some content...

Note:
This will only display in the notes window.
````

If someone is interested by the other syntax, please open a new issue so we could discuss support. This is not built-in Pandoc so we would need a Lua Filter to allow this.
