### ISSUE TITLE
Add functionality for reveal.js-menu

### ISSUE THREAD

**Issue by Emaasit** [rstudio/revealjs#46]
Another great plugin to have is a slideout menu for navigating reveal.js presentations, to jump between slides. Here is a demo: [https://denehyg.github.io/reveal.js-menu/#/home](https://denehyg.github.io/reveal.js-menu/#/home)

Github code for `reveal.js-menu` is here: [https://github.com/denehyg/reveal.js-menu](https://github.com/denehyg/reveal.js-menu)

**Comment by jjallaire** [comment]
Implemented here: https://github.com/rstudio/revealjs/commit/064552c4b5641ae5e156d0d0b6977dd507519cba

**Comment by Emaasit** [comment]
Thanks JJ.

**Comment by stevepowell99** [comment]
awesome JJ. Can the options for the plugin be configured in the YAML?
