### ISSUE TITLE
Display images on 2D slides

### ISSUE THREAD

**Issue by tbarbier** [rstudio/revealjs#49]
Hi!

Naive question here but I could not find any answer around.
I am trying to build a 2D presentation (horizontal + vertical slides) but when I embed a figure in the slide, it is only displayed on vertical images (##) and not on horizontal ones (#).
Is there any way to fix that?

Thanks!

Thibault

**Comment by jjallaire** [comment]
No, the 2D slides are unfortunately just headers/transitions.

**Comment by tbarbier** [comment]
That's too bad... Thank you very much!

**Comment by dimagor** [comment]
I found the workaround by @vspinu at the bottom of #40 helpful:

```
<section class="titleslide level1">
<h1>TOP SLIDE</h1>

FIGURES/TEXT

## SUBSLIDE

FIGURES/TEXT
</section>
```

**Comment by cderv** [comment]
Same as #40 - this now works since Pandoc 2.7

````markdown
---
title: content on slides
output:
  revealjs::revealjs_presentation: default
---

# mtcars graph

```{r, echo = FALSE}
plot(mtcars)
```

## Looking at the data 

```{r}
head(mtcars)
```

````
