### ISSUE TITLE
Support leaflet in revealjs presentations

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/revealjs#50]
http://stackoverflow.com/questions/35894401/how-to-include-leaflet-for-r-output-into-rmarkdown-presentation

Is this something we can fix on our end or is it a problem upstream with the javascript libraries?

I'm having to fall back to ioslides/slidify just because I'm unable to display a map...

Related: https://github.com/rstudio/revealjs/issues/11

**Comment by jjallaire** [comment]
I don't know enough about leaflet to say. When I try the simple repro in the SO article I get a map but a bunch of 404s because it appears to be attempting to load tiles from the local filesystem.

@bhaskarvk or @jcheng5 Any idea here?

**Comment by bhaskarvk** [comment]
@jjallaire The issue you're seeing has been fixed in GH master, but CRAN ver. still has that problem.

**Comment by bhaskarvk** [comment]
@kevinykuo Try the widgetframe package for separating widget deps from the document deps.

**Comment by jjallaire** [comment]
Thanks @bhaskarvk!

**Comment by cderv** [comment]
The example from the SO post is now working. 

````markdown
---
title: "Rmarkdown Presentation including Leaflet"
output: 
  revealjs::revealjs_presentation
---

Show "Leaflet for R" within Rmarkdown presentation: fails.

```{r}
library(leaflet)
leaflet() %>%
  addTiles %>% # Add default OpenStreetMap map tiles
  setView(lng = 5.0, lat = 51.0, zoom = 6)
```
````

If there are other issues with **leaflet** please open a new issue.
