### ISSUE TITLE
DOC: request - how to add a background image to presentation?

### ISSUE THREAD

**Issue by stnava** [rstudio/revealjs#6]
hi - thanks for this ... it's definitely my preferred style of rmarkdown presentation.  one thing i'd like to know is whether it's possible to have a background image cover a slide.  e.g. as in:

[slide 10 at reveal-js example](http://lab.hakim.se/reveal-js/#/10)

any advice appreciated.

**Comment by jjallaire** [comment]
If this were possible it would need to be supported by the pandoc reveal.js
engine and right now it looks like it's not.

**Comment by junkka** [comment]
This is possible using the pandoc [header_attribute extension](http://pandoc.org/README.html#header-identifiers-in-html-latex-and-context) 

    # My header {data-background="image.png"}

**Comment by mh74** [comment]
In terms of background images, junkka solution works.  But for the title page, how do we embed an image there?

**Comment by MarcinKosinski** [comment]
I am also looking for the solution to insert an image in the title page of the presentation

**Comment by MarcinKosinski** [comment]
@mh74  here is the solution
https://github.com/rstudio/revealjs/issues/32

@jjallaire  This issue can be closed now.
