### ISSUE TITLE
Slide Size Settings

### ISSUE THREAD

**Issue by hathawayj** [rstudio/revealjs#60]
I see [here](https://github.com/hakimel/reveal.js#presentation-size) the code to set the presentation size.  However, I can't seem to find an example of how to implement this using the RStudio implementation of revealjs. 

* Is there a YAML setting for these reveal options?
* or How do I implement the code below into my `Rmd` file?

```
Reveal.initialize({

	...

	width: "100%",
	height: "100%",
	margin: 0,
	minScale: 1,
	maxScale: 1
});
```

**Comment by hathawayj** [comment]
I now see it in the  `revealjs::revealjs_presentation()` function under `reveal_options`.

**Comment by kohlkopf** [comment]
It would be helpful for you to close the issue as you've found a solution @hathawayj .

**Comment by cderv** [comment]
For reference, this can be done this way: 

````markdown
---
output:
  revealjs::revealjs_presentation:
    reveal_options:
      width: "100%"
      height: "100%"
      margin: 0
      minScale: 1
      maxScale: 1
---
````

I have created an issue to track better doc of supported options: #119
