### ISSUE TITLE
reveals conflicts with RStudio "knit" option

### ISSUE THREAD

**Issue by grayskripko** [rstudio/revealjs#64]
I've finally found that your package is the only reason why RStudio stopped to knit anything.
When I remove the package from my .libPath() everything works fine.
When I get back it I have:
- knit button without drop-down arrow and list
![image](https://user-images.githubusercontent.com/10427026/41870139-75ebd262-78bb-11e8-9596-37690a782f76.png)
- not working rendering of my Rmd files
![image](https://user-images.githubusercontent.com/10427026/41870116-698bc7ac-78bb-11e8-91fd-c9962149bdd1.png)
As you can see it doesn't generate html file now.
I've checked it for different output options.
It was a very sudden and frustrating bug

**Comment by grayskripko** [comment]
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.0 slidify_0.5    magrittr_1.5   markdown_0.8   tools_3.5.0    whisker_0.3-2  yaml_2.1.19    stringi_1.1.7 
 [9] knitr_1.20     stringr_1.3.1

**Comment by grayskripko** [comment]
I have the last version of RStudio

**Comment by grayskripko** [comment]
Sorry, this is not the problem. Still trying to understand the logic why this button works and doesn't work occasionally without any reason on reloading RStudio

**Comment by jjallaire** [comment]
There is a mechanism that allows overriding of the Knit button for certain formats and if certain code in the .Rprofile. Is there a custom markdown rendered registered in your .Rprofile? (`getOption("rstudio.markdownToHTML")` would detect when this is registered)

Also, there is a mechanism by which packages can override the Knit button for their own rendering. Slidfy is one of those packages so I'd expect that when viewing a Slidfy presentation (I noticed it's in your set of loaded packages) that the Knit button would exhibit the behavior you are seeing).
