### ISSUE TITLE
data-background-interactive

### ISSUE THREAD

**Issue by sergiballestar** [rstudio/revealjs#67]
Hey,

If it is possible to use webs as interactive iframe backgrounds, why is this not working to me? Is this already implemented in R studio's package for .Rmd files? 

https://github.com/hakimel/reveal.js/issues/1974
https://github.com/hakimel/reveal.js#iframe-backgrounds

I am able to load a .html file but won't fill the full screen as it's not in the background, and if I set it as background it won't be intereactive.

Any ideas?

**Comment by Hamcastle** [comment]
Any follow up on this?

**Comment by thoughtpalette** [comment]
radio silence?

**Comment by SamGuay** [comment]
This seems to be working on my end with this bit of code: 

```markdown
## Is it interactive? {data-background-iframe="https://xkcd.com"}
```
![interactive](https://user-images.githubusercontent.com/30598330/112771569-7146e680-8ffa-11eb-8cd7-356d568691d8.gif)

**Comment by apreshill** [comment]
Can confirm, this also works: `## Is it interactive? {background-iframe="https://xkcd.com"}` (i.e., with or without the `data-` prefix) using revealjs via Pandoc.

**Comment by rleyvasal** [comment]
It does not work for me 

````markdown
---
title: "Untitled"
date: ""
author: ""
output: 
  revealjs::revealjs_presentation:
    incremental: true
    highlight: pygments
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Is it interactive? {background-iframe="https://xkcd.com"}

- fraction 
  $$\frac{a}{b}$$ 
````

![frame](https://user-images.githubusercontent.com/61335136/130516626-3c08b2aa-bac8-4314-9781-c123aacb622c.gif)

**Comment by cderv** [comment]
It should work, in the sense that you should have a blank page. Did you open inside RStudio Preview pane or Browser window ? RStudio IDE has limitation (for security maybe ?) regarding iframes or videos in HTML doc I think, so try in a browser. (it is the case for me)

````markdown
---
title: "Untitled"
output: revealjs::revealjs_presentation
---

## Is it interactive? {background-iframe="https://xkcd.com"}

This presentation must be open in a browser, as the iframe won't show in rstudio preview pane
````

However, not all the component are interactive when using `revealjs::revealjs_presentation`. It works ok with Pandoc directly as @apreshill mentioned. It is probably an issue with revealjs version used in this package. We'll make sure to check when we'll update.

**Comment by rleyvasal** [comment]
@cderv, It works in a Browser window -   RStudio Preview was my issue.

**Comment by cderv** [comment]
I'll close this because this is working already, and will probably work better when we'll update.
