### ISSUE TITLE
Reveal.js incremental option doesn't apply to code chunks

### ISSUE THREAD

**Issue by cgrudz** [rstudio/revealjs#70]
# System details
```
RStudio Edition : Desktop
RStudio Version : 1.2.5001
OS Version      :  Ubuntu 18.04.3 LTS
R Version       :  3.4.4 (2018-03-15)
```
## Issue

When using the revealjs package in R Markdown we can set the incremental option for bullets in the text as in the yaml frontmatter.

```{markdown}
---
title: "Reveal Template"
output:
  revealjs::revealjs_presentation:
    incremental: true
---

## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Code and Output
- A summary of cars data

```{r}
summary(cars)
```

However, this doesn't apply to code chunks or their output which is rendered statically on the page.

For teaching, I would like to apply the fade-in to code chunks as well, for staging questions to students.  Can this feature be included?

**Comment by atusy** [comment]
Try following code.
I think the feature will be too complex to implement in revealjs.
In addition, incremental list is actually the feature provided by Pandoc.

````
---
title: "Untitled"
output: 
  revealjs::revealjs_presentation:
    incremental: TRUE
    keep_md: TRUE
---

# Iris

```{css, echo=FALSE}
.incremental-chunk ul {
  width: 100%;
  text-align: inherit;
}
.incremental-chunk li {
  list-style: none;
}
```

```{r, include=FALSE}
local({
  itemize_string <- function(x) {
    out <- paste0('  ', strsplit(x, '\n')[[1L]])
    out[out == '  '] <- ''
    out <- paste0(out, collapse = '\n')
    out <- gsub('^(\\n*)  ', '\\1- ', out)
    out
  }
  itemize_hook <- function(f) {
    force(f)
    function(x, options) {
      if (isTRUE(options$incremental)) {
        itemize_string(f(x, options))
      } else {
        f(x, options)
      }
    }
  }
  knitr::knit_hooks$set(
    source = itemize_hook(knitr::knit_hooks$get('source')),
    output = itemize_hook(knitr::knit_hooks$get('output')),
    plot = itemize_hook(knitr::knit_hooks$get('plot')),
    incremental = function(options, before) {
      if (options$incremental) {
        if (before) {
          '\n\n`<div class="incremental-chunk">`{=html}\n\n'
        } else {
          '\n\n`<div>`{=html}\n\n'
        }
      }
    }
  )
  
  if (require(htmlwidgets)) {
    knit_print <- knitr::knit_print
    knit_print_htmlwidget <-  getS3method('knit_print', 'htmlwidget')
    knit_print.htmlwidget <- function(x, options, ...) {
      res <- knit_print_htmlwidget(x, options = options, ...)
      if (isTRUE(options$incremental)) {
        current_attributes <- attributes(res)
        res <- itemize_string(res)
        attributes(res) <- current_attributes
      }
      return(res)
    }
    registerS3method('knit_print', 'htmlwidget', knit_print.htmlwidget)
  }
})
```


```{r, fig.height=2, incremental=TRUE}
names(iris)
ggplot2::qplot(iris$Sepal.Length, iris$Sepal.Width)
```
````

**Comment by cgrudz** [comment]
Thanks for this, it does appear to work, but this seems maybe more difficult of a solution than I was imagining.  The behavior where code chunks are also incremental is the default option in .rpres file types.  I don't know if the above will be totally practical for longer lecture materials.

**Comment by atusy** [comment]
@cgrudz Just omit the following like and you'll see source are displayed by default.

```r
 source = itemize_hook(knitr::knit_hooks$get('source')),
```

**Comment by rleyvasal** [comment]
I am able to change the behavior of code chuck to incremental in `slidy_presentation`  with `<ul>`  and `<li>`  tags; however the code below does not work in `revealjs`

It would be helpful to have chunk codes work with the `incremental` option in `revealjs`

```
---
title: "Untitled"
output: 
  slidy_presentation:
    incremental: true
---

## Slide 1

- fraction

  $$\frac{a}{b}$$

## Slide with Plot

-   plot 1


<ul class="incremental">
<li>
```{r pressure}
plot(pressure)
```

</li>
</ul>
```

![chunk_code](https://user-images.githubusercontent.com/61335136/129951402-ee3416c9-de9e-4fd3-80ac-dcba8aacd330.gif)

**Comment by cderv** [comment]
As @atusy shared, revealjs incremental feature is brought by Pandoc and it works for list. 

So this would work 
```r
---
title: "Reveal Template"
output:
  revealjs::revealjs_presentation:
    incremental: true
---

## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Code and Output
- A summary of cars data

- 
  ```{r}
  summary(cars)
  ```

```

But you will get a bullet point (or other marker) before the code chunk. It could be change or hidden using CSS maybe. 

We'll consider what we could to improve this in the limit of what Pandoc can offer us.

**Comment by rleyvasal** [comment]
Thanks @cderv, your code makes the the summary and a plot work with `incremental` option - Note that the chunk code has to be `indented` to work .

 However, when I tried to make an interactive graph `echarts4r` work with `incremental` option, using the same strategy - it doesn't work. look at example below:
````
---
title: "Untitled"
output: 
  revealjs::revealjs_presentation:
    incremental: true
---

## Slide 1

- fraction
 $$\frac{a}{b}$$

## Slide with Plot

-   plot 1

-
  ```{r pressure, echo=FALSE}
  plot(pressure)
  ```

## Slide with Plot 2

-   plot 2

```{r message=FALSE, warning=FALSE, include=FALSE}
  library(pacman)
  p_load(tidyverse, echarts4r)
```

-   
  ```{r echo=FALSE, message=FALSE}
      mtcars  |> e_charts() |>
        e_boxplot(mpg) |>
        e_boxplot(disp) |>
        e_boxplot(hp) |>
        e_title("Unit Sales Per Month") |>
        e_tooltip(trigger = "axis") 
  ```


````


![interactive_graph](https://user-images.githubusercontent.com/61335136/130119527-7734b3dd-f848-4142-9726-30d40d233734.gif)

**Comment by cderv** [comment]
I believe this is a CSS issue and a matter of support by revealjs and Pandoc. 

I don't have a solution right now. You can try tweaking revealjs CSS and HTML, but currently the incremental option is only expected to work with bullet point. It seems inserting a widget inside a bullet point is not allowing revealjs to extend the size of the div for the incremental bullet. Maybe tweaking CSS will help. 

We have in mind all this limitations, and we'll try to see what can be done considering new revealjs version and current Pandoc support

**Comment by cderv** [comment]
In fact, I think the `incremental` option should really be used only for content that works in bulleted list. After all this is a feature called "incremental list" by Pandoc (https://pandoc.org/MANUAL.html#incremental-lists)

For content like plots or code chunk, I think the pausing feature should be used (https://pandoc.org/MANUAL.html#inserting-pauses) 

@rleyvasal your example would be 
````markdown
---
title: "Untitled"
output: 
  revealjs::revealjs_presentation:
    incremental: false
---

## Slide 1

fraction

. . .

$$\frac{a}{b}$$

## Slide with Plot

plot 1

. . .

```{r pressure, echo=FALSE}
plot(pressure)
```

## Slide with Plot 2

plot 2

. . .

```{r message=FALSE, warning=FALSE, include=FALSE}
  library(pacman)
  p_load(tidyverse, echarts4r)
```

. . . 

```{r echo=FALSE}
    mtcars  |> e_charts() |>
      e_boxplot(mpg) |>
      e_boxplot(disp) |>
      e_boxplot(hp) |>
      e_title("Unit Sales Per Month") |>
      e_tooltip(trigger = "axis") 
```

## Slide with Plot 2 without bulletpoint

```{r echo=FALSE}
    mtcars  |> e_charts() |>
      e_boxplot(mpg) |>
      e_boxplot(disp) |>
      e_boxplot(hp) |>
      e_title("Boxplot") |>
      e_tooltip(trigger = "axis") 
```
````

@cgrudz yours would be 
````markdown
---
title: "Reveal Template"
output:
  revealjs::revealjs_presentation:
    incremental: false
---

## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Code and Output

A summary of cars data

. . .

```{r}
summary(cars)
```
````

This clearly requires some more documentation, especially because you can also use directly the `fragment` class to create revealing content. 

We are tracking this here #120 where you can find more experiment with the different available syntax

I'll close this as we have a suitable solution I believe. 

Please reopen if something is still missing in the desired behavior.

**Comment by oraclejavanet** [comment]
Thanks,
Jeff

Jeffrey M. Hunter
Senior DBA, Mathematical Programmer, Author
***@***.***
www.idevelopment.info

A computer without a Microsoft operating system is like a dog without bricks tied to its head.

God rot Windows and all its ugly, clunky, badly-designed horror.
Stephen Fry
