### ISSUE TITLE
'embedded' https web pages not showing up ('frowning face')

### ISSUE THREAD

**Issue by daaronr** [rstudio/revealjs#71]
Using rstudio default reveal.js template:

```
---
title: "Untitled"
output: revealjs::revealjs_presentation
---

## R Markdown

## Embed a web page as a background {data-background-iframe="https://www.cnn.com"}

```

The web page does not show up (in preview in rstudio) and if I view it in the browser (Chrome) I get a small frowning folded page icon

Addendum: viewing it in firefox it says 
> Blocked by Content Security Policy

> An error occurred during a connection to edition.cnn.com.

> Firefox prevented this page from loading in this way because the page has a content security policy that disallows it.

So this seems to work for http not https sites only!

**Comment by cderv** [comment]
Possible related to #67

**Comment by cderv** [comment]
I think this is highly dependant of the Content Security Policy of the website you are trying to iframe. 
Not all website allow that and this is partly control by there [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy)

There error we have in browser console is: 
```
Refused to frame 'https://edition.cnn.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' https://*.cnn.com:* http://*.cnn.com:* https://*.cnn.io:* http://*.cnn.io:* *.turner.com:* https://www.google.com https://news.google.com https://www.google.co.uk https://amp-cnn-com.cdn.ampproject.org courageousstudio.com".
```

which seems to indicate than only the whitelisted site can iframe this one. See [`frame-ancestor`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors)

The example in https://github.com/rstudio/revealjs/issues/67#issuecomment-808977809 is working 
````markdown
---
title: "Untitled"
output: revealjs::revealjs_presentation
---

# Embed a web page as a background {data-background-iframe="https://xkcd.com"}

````

So I don't think there is any issue with this feature.
