### ISSUE TITLE
Some options in reveal_options are surrounded by two pairs of single quotes

### ISSUE THREAD

**Issue by iain-palmer** [rstudio/revealjs#72]
Some settings in reveal_options get surrounded by an extra set of single-quotes. For example, in the Rmd file, these settings:
> parallaxBackgroundImage: "https://s3.amazonaws.com/hakim-static/reveal-js/reveal-parallax-1.jpg"
> parallaxBackgroundSize: "2100px 900px"

Become (in the html):     

> parallaxBackgroundImage: ''https://s3.amazonaws.com/hakim-static/reveal-js/reveal-parallax-1.jpg''
> parallaxBackgroundSize: ''2100px 900px''

With a pair of single quotes either side. The extra set of single quotes in the html then need to be manually deleted.

**Comment by jjallaire** [comment]
Could you provide a full example? (your Rmd source that yields this).

**Comment by iain-palmer** [comment]
Please see these files:
[revealjs_issue72_example.zip](https://github.com/rstudio/revealjs/files/3768753/revealjs_issue72_example.zip)
- **revealjs_issue72_example.Rmd** - example Rmd file
- **revealjs_issue72_example.html** - html file output from the above (doesn't display properly in chrome)
- **revealjs_issue72_example_modified.html** - html file with lines 6548 & 6550 manually edited (_does_ display properly in chrome)

Hope this helps!
Iain

**Comment by jjallaire** [comment]
Okay, thanks, that's very helpful!

Should be fixed here: https://github.com/rstudio/revealjs/commit/633c05f47dca23c48382804bd8d0cf9d55d018bb

**Comment by iain-palmer** [comment]
Checked, works for me now. Thank you!
