### ISSUE TITLE
Code highlighting not working

### ISSUE THREAD

**Issue by reginaldo-re** [rstudio/revealjs#76]
I tried to use source code chunks in slides (C, C++, Java, Python) without success. Does anyone make syntax highlight work?

**Comment by cderv** [comment]
Here is an Rmd example 

````markdown
---
title: "Test"
output: 
  revealjs::revealjs_presentation:
    self_contained: false
    keep_md: true
---

# C

```c
void square(double *x) {
  *x = *x * *x;
}
```

# Cpp

```cpp
// Your First C++ Program

#include <iostream>

int main() {
    std::cout << "Hello World!";
    return 0;
}

```

# JAVA

```java
public class HelloWorld  {

    public static void main( String [] args ) {
        System.out.println( "Hello World" );
    }

}
```

# Python

```python
import matplotlib.pyplot as plt
plt.plot([0, 2, 1, 4])
plt.show()
```
````

This is working as describe in https://github.com/rstudio/revealjs#appearance-and-style 
Default is using Pandoc `pygments` style. Any of of Pandoc's supported style can be set. 

I'll close. Please reopen if I missed something. 

Or open a new issue if there is a new problem.
