### ISSUE TITLE
Hide navigation buttons

### ISSUE THREAD

**Issue by mafw** [rstudio/revealjs#78]
Is there a way to hide the navigation buttons that appear on the slides? I've tried:
`controls: false` as documented here:https://github.com/hakimel/reveal.js#configuration.

Below is the icon I am talking about: 
![Screenshot from 2020-04-27 14-16-03](https://user-images.githubusercontent.com/31126924/80371127-afd79c80-8891-11ea-8eae-b59ae7df8c2f.png)

**Comment by karldw** [comment]
@mafw, are you putting the argument in the `reveal_options` section? This works for me:

```
---
output:
  revealjs::revealjs_presentation:
    reveal_options:
        controls: false
---
```

**Comment by mafw** [comment]
This works perfectly, thank you! I was not putting the argument in the correct sections...
