### ISSUE TITLE
Controlling size of text

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/revealjs#9]
Is there a `.smaller` option similar to that in ioslides?

With a slightly longer title or section headers I find much of my content overflowing.

**Comment by jjallaire** [comment]
You could add some custom CSS to either an included HTML file, a file
referenced by the `css` YAML header, or even inline, e.g.

<style type="text/css">
.reveal h1 { font-size: 2.5em; }
</style>

**Comment by ChihChengLiang** [comment]
the `css` YAML header seems not working. I checked the resource in the browser, the stylesheet is not loaded.

**Comment by cderv** [comment]
Currently this would require some CSS. Example using inline CSS using chunk option
````markdown
---
title: CSS custom
output: 
  revealjs::revealjs_presentation: default
---

# Normal slide 

```{css, echo = FALSE}
.reveal .smaller p {
  font-size: 50%
}
```

Normal text

# Plotly {.smaller}

Some smaller text
````

This would also work using the css argument in `revealjs_presentation`

````markdown
---
title: CSS custom
output: 
  revealjs::revealjs_presentation: 
    css: style.css
---

# Normal slide 

Normal text

# Plotly {.smaller}

Some smaller text
````

Note that reveal.js includes in its text a small-like style when using the [`<small>` HTML tag](https://www.w3schools.com/tags/tag_small.asp)

Notes regarding what could be done:

* reveal.js 4+ has now the possibility through the theme to change some CSS root variable. This could help for changing global sizing like this. 
* Themes are also available through SCSS, so something dynamic like **bslib** could be probably done to use SCSS variable to create a custom theme on the fly. 

We'll follow this in #95
