### ISSUE TITLE
Reveal.js incremental option doesn't apply to Latex formulas

### ISSUE THREAD

**Issue by rleyvasal** [rstudio/revealjs#99]
# Issue
Latex in slide static when using incremental option - bullets still appear incremental.

\## Slide 1
\-    fraction

$$\frac{a}{b}$$

# Expected 

Latex should be incremental same as bullet points

**Comment by cderv** [comment]
What is exactly the behavior you expect ? 
Is it the equation inside the first bullet point and to appear with the bullet point ? 

For that, you need to make sure that the equation is indented correctly to be part of the bullet point. 

Try this 

````markdown
---
title: "Untitled"
output: 
  revealjs::revealjs_presentation:
    incremental: true
---

## Slide 1

- fraction

  $$\frac{a}{b}$$
````

![reveal-increment](https://user-images.githubusercontent.com/6791940/129700049-88c7babd-f7e3-4897-ad32-7cc88773a68b.gif)

**Comment by rleyvasal** [comment]
# Expected output: same as an R presentation (code below), bullet first, then the Latex)
```
Rpresentation
========================================================
author: 
date: 
autosize: true
incremental: true

Slide 1
========================================================

- fraction

  $$\frac{a}{b}$$   
```

btw: how do you take the animated screenshot?

**Comment by cderv** [comment]
I believe this is not supported by Pandoc directly. The feature is called incremental list: https://pandoc.org/MANUAL.html#incremental-lists
So I believe that unless you also use a list item for the math element, it won't work. You cannot make any paragraph line incremental with this feature.

It is powered by Pandoc directly and it is unlikely we will change that in revealjs directly.

**Comment by rleyvasal** [comment]
Just as a side note, I was able to override the behavior in `slidy_presentation` with `<ul>` and `<li>` tags as shown below; however, this code does not work in `revealjs_presentation`

```
# Slide with Bullets

<ul class="incremental">

<li>
fraction
</li>

<li>
  $$\frac{a}{b}$$ 
</li>

</ul>
```

**Comment by rleyvasal** [comment]
Adding `-` infront of the Latex formula makes Latex incremental with a bullet point - It would be better if it appeared without bullet point like `R presentation`, but this works for now.

```
# Slide with Bullets

- fraction
- $$\frac{a}{b}$$ 

```
![slide](https://user-images.githubusercontent.com/61335136/129937233-864c8a01-67bd-44c5-8916-0d0ceee38312.gif)

**Comment by cderv** [comment]
Yes I said if you use a list item for the math element it works. So adding the dash is the easy solution. Thanks for sharing that it works ok. 

You could try custom css to remove (hide) the marker maybe. 

If you want to use HTML directly this is a solution. You just need to use the syntax compatible with revealjs, which is probably different from slidy. You can inspect the resulting HTML code to see what it looks like to set the correct classes on the node.

**Comment by cderv** [comment]
Now looking closer on how reveal.js is working and knowing better Pandoc feature, here is the way to do incremental revealing of content on a slide: Use pausing ! 

````markdown
---
title: Incremental reveal
output: 
  revealjs::revealjs_presentation: default
---

# Pausing in slide content

fraction will come next 

. . .

$$\frac{a}{b}$$ 

# Next slide

Conclusion
````

`. . .` is a special Pandoc syntax (https://pandoc.org/MANUAL.html#inserting-pauses) that will transform into reveal fragment features. See #120 for more experiment on supported syntax using reveal.js `fragment` class.

I'll close this now because it seems like a suitable answer that does not rely on [Incremental List](https://pandoc.org/MANUAL.html#incremental-lists) where list are not desired here.
